org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.1.2
minecraft_target_label=26.1.x
minecraft_version_range=[26.1,26.1.3)
neo_version=26.1.2.78
neo_version_range=[26.1.0,)
loader_version_range=[1,)

mod_id=placeable
mod_name=Placeable Plants: Expanded
mod_license=MIT
mod_version=1.0.7
mod_group_id=it.bisumto
mod_authors=BisUmTo, Pathmakers Studio
mod_description=An unofficial expanded fork of Placeable Plants with broad vanilla and modded plant support.
