package it.bisumto.placeable;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.neoforge.common.ModConfigSpec;

import java.util.List;

public class PlaceableConfig {
    public static final ModConfigSpec SPEC;

    public static final ModConfigSpec.ConfigValue<List<? extends String>> PLACEMENT_BLACKLIST;
    public static final ModConfigSpec.ConfigValue<List<? extends String>> WORLDGEN_BLACKLIST;
    public static final ModConfigSpec.BooleanValue DISABLE_EXPANDED_WORLDGEN_PLACEMENT;
    public static final ModConfigSpec.ConfigValue<List<? extends String>> ADDITIONAL_PLACEABLE_PLANTS;

    static {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();

        builder.push("placement");

        PLACEMENT_BLACKLIST = builder
                .comment(
                        "Blocks or block tags that plants are NOT allowed to be placed on at all, including manual player placement and world generation.",
                        "Use block ids like 'minecraft:stone' or tag ids prefixed with '#', like '#minecraft:leaves'.",
                        "Empty by default, so players can still manually place plants on leaves or other solid blocks."
                )
                .defineListAllowEmpty(
                        List.of("placement_blacklist"),
                        () -> List.of(),
                        PlaceableConfig::isValidBlacklistEntry
                );

        WORLDGEN_BLACKLIST = builder
                .comment(
                        "Blocks or block tags that plants are NOT allowed to generate on during world generation.",
                        "This does not affect manual player placement.",
                        "Use block ids like 'minecraft:stone' or tag ids prefixed with '#', like '#minecraft:leaves'.",
                        "Default blocks leaves, so plants should not naturally generate on top of leaf blocks."
                )
                .defineListAllowEmpty(
                        List.of("worldgen_blacklist"),
                        () -> List.of("#minecraft:leaves"),
                        PlaceableConfig::isValidBlacklistEntry
                );

        DISABLE_EXPANDED_WORLDGEN_PLACEMENT = builder
                .comment(
                        "Globally disables this mod's expanded plant-placement rules during world generation.",
                        "When true, plants generated by worldgen keep their normal vanilla/modded soil checks instead of generating on any solid non-soil block.",
                        "Manual player placement is not affected by this option.",
                        "When this is enabled, worldgen_blacklist is effectively unnecessary because expanded worldgen placement is skipped entirely."
                )
                .define("disable_expanded_worldgen_placement", false);

        ADDITIONAL_PLACEABLE_PLANTS = builder
                .comment(
                        "Optional plant block ids or block tags that should use the mod's expanded placement rules even if they are normally kept vanilla-only.",
                        "Useful for decorative/building setups where you want to allow specific saplings, crops, berry bushes, nether wart, or similar VegetationBlock-based plants on non-soil blocks.",
                        "Use plant block ids like 'minecraft:oak_sapling' or tag ids prefixed with '#', like '#minecraft:saplings'.",
                        "Empty by default to preserve vanilla behavior for crops, saplings, and similar functional plants."
                )
                .defineListAllowEmpty(
                        List.of("additional_placeable_plants"),
                        () -> List.of(),
                        PlaceableConfig::isValidBlacklistEntry
                );

        builder.pop();

        SPEC = builder.build();
    }

    private static boolean isValidBlacklistEntry(Object value) {
        if (!(value instanceof String entry)) {
            return false;
        }

        entry = entry.trim();
        if (entry.isEmpty()) {
            return false;
        }

        if (entry.startsWith("#")) {
            return parseIdentifier(entry.substring(1)) != null;
        }

        return parseIdentifier(entry) != null;
    }

    private static Identifier parseIdentifier(String value) {
        try {
            return Identifier.parse(value);
        } catch (Exception ignored) {
            return null;
        }
    }

    public static boolean isBlacklistedFloor(BlockState state, boolean worldgen) {
        if (matchesBlacklist(state, PLACEMENT_BLACKLIST.get())) {
            return true;
        }

        return worldgen && matchesBlacklist(state, WORLDGEN_BLACKLIST.get());
    }

    public static boolean shouldSkipExpandedWorldgenPlacement(boolean worldgen) {
        return worldgen && DISABLE_EXPANDED_WORLDGEN_PLACEMENT.get();
    }

    public static boolean isAdditionalPlaceablePlant(BlockState state) {
        return matchesBlacklist(state, ADDITIONAL_PLACEABLE_PLANTS.get());
    }

    private static boolean matchesBlacklist(BlockState state, List<? extends String> entries) {
        if (entries.isEmpty()) {
            return false;
        }

        for (String rawEntry : entries) {
            String entry = rawEntry.trim();

            if (entry.startsWith("#")) {
                Identifier tagId = parseIdentifier(entry.substring(1));
                if (tagId != null) {
                    TagKey<Block> tag = TagKey.create(Registries.BLOCK, tagId);
                    if (state.is(tag)) {
                        return true;
                    }
                }
            } else {
                Identifier blockId = parseIdentifier(entry);
                if (blockId != null && BuiltInRegistries.BLOCK.getOptional(blockId).filter(state::is).isPresent()) {
                    return true;
                }
            }
        }

        return false;
    }
}
